language: node_js
node_js:
  - "4.1"

sudo: required
dist: trusty

before_script:
  - sleep 15
  - sudo apt-get update -qq
  - sudo apt-get install -y libicu52 libjpeg8 libfontconfig libwebp5
  - mongo
  - use express
  - db.createCollection('uploadProgress')
  - db.createCollection('file')
  - exit
  - npm install -g gulp
  - npm install -g jasmine-node
  - cd server
  - npm install
  - cd ..
  - rvm 2.2.3
  - gem install scss_lint
  - bash setup.sh

script:
  - nohup node server/server.js --config=test/config &
  - gulp all
  - gulp dist
  - jasmine-node test/jasmine-node/

services:
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - sleep 15
  - mongodb

after_script:
  - cat nohup.out

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
  code_climate:
    repo_token: 4b9bad2eb36ad49fa1af9b04b49cf4e068dcb6086a5e216fccf988221479118a
