language: node_js
node_js:
  - "4.1"

sudo: required
dist: trusty

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libicu52 libjpeg8 libfontconfig libwebp5
  - npm install -g gulp
  - npm install -g jasmine-node
  - bower install
  - cd server
  - npm install
  - cd ..

script:
  - gulp
  - bash setup.sh
  - nohup node server/server.js --config=test/config &
  - gulp test
  - gulp clean
  - jasmine-node test/jasmine-node/

after_script:
  - cat nohup.out